using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace RaceDay.Api;
[ApiController, Route("api/auth")] public class AuthController(RaceDayDbContext db,TokenService tokens):ControllerBase {
 [HttpPost("register")] public async Task<IActionResult> Register(RegisterRequest r) { if (!Enum.TryParse<UserRole>(r.Role,true,out var role)||string.IsNullOrWhiteSpace(r.Password)||r.Password.Length<8) return BadRequest("Use Organiser or Participant and a password of at least 8 characters."); if(await db.Users.AnyAsync(u=>u.Email==r.Email||u.Username==r.Username)) return BadRequest("Username or email already exists."); var u=new User{Username=r.Username,Email=r.Email,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),Role=role.ToString()}; db.Users.Add(u); if(role==UserRole.Organiser) { if(string.IsNullOrWhiteSpace(r.OrganisationName)||string.IsNullOrWhiteSpace(r.ContactName)||string.IsNullOrWhiteSpace(r.Phone)) return BadRequest("Organiser details are required."); db.Organizers.Add(new Organizer{User=u,OrganisationName=r.OrganisationName,ContactName=r.ContactName,Phone=r.Phone}); } else { if(string.IsNullOrWhiteSpace(r.FirstName)||string.IsNullOrWhiteSpace(r.LastName)||r.DateOfBirth is null||string.IsNullOrWhiteSpace(r.Gender)||string.IsNullOrWhiteSpace(r.EmergencyContact)) return BadRequest("Participant details are required."); db.Participants.Add(new Participant{User=u,FirstName=r.FirstName,LastName=r.LastName,DateOfBirth=r.DateOfBirth.Value,Gender=r.Gender,EmergencyContact=r.EmergencyContact}); } await db.SaveChangesAsync(); return Created("api/users/profile",new{u.UserId,u.Username,u.Email,u.Role,token=tokens.Create(u)}); }
 [HttpPost("login")] public async Task<IActionResult> Login(LoginRequest r) { var u=await db.Users.SingleOrDefaultAsync(x=>x.Username==r.UsernameOrEmail||x.Email==r.UsernameOrEmail); return u is null||!BCrypt.Net.BCrypt.Verify(r.Password,u.PasswordHash)?Unauthorized():Ok(new{u.UserId,u.Username,u.Email,u.Role,token=tokens.Create(u)}); }
}
[ApiController] public class CategoriesController(RaceDayDbContext db):ControllerBase {
 [HttpGet("api/events/{eventId:int}/categories")] public async Task<IActionResult> List(int eventId){if(!await db.Events.AnyAsync(x=>x.EventId==eventId))return NotFound();return Ok(await db.Categories.Where(x=>x.EventId==eventId).ToListAsync());}
 [HttpPost("api/events/{eventId:int}/categories"),Authorize(Roles="Organiser")] public async Task<IActionResult> Create(int eventId,CategoryRequest r){var e=await Owned(eventId);if(e is null)return Forbid();if(!Valid(r))return BadRequest();var c=new Category{EventId=eventId,CategoryName=r.CategoryName,Distance=r.Distance,MinAge=r.MinAge,MaxAge=r.MaxAge,EntryFee=r.EntryFee};db.Categories.Add(c);await db.SaveChangesAsync();return Created($"api/categories/{c.CategoryId}",c);}
 [HttpPut("api/categories/{id:int}"),Authorize(Roles="Organiser")] public async Task<IActionResult> Update(int id,CategoryRequest r){var c=await db.Categories.Include(x=>x.Event).SingleOrDefaultAsync(x=>x.CategoryId==id);if(c is null)return NotFound();if(!await IsOwner(c.Event))return Forbid();if(!Valid(r))return BadRequest();(c.CategoryName,c.Distance,c.MinAge,c.MaxAge,c.EntryFee)=(r.CategoryName,r.Distance,r.MinAge,r.MaxAge,r.EntryFee);await db.SaveChangesAsync();return Ok(c);}
 [HttpDelete("api/categories/{id:int}"),Authorize(Roles="Organiser")] public async Task<IActionResult> Delete(int id){var c=await db.Categories.Include(x=>x.Event).SingleOrDefaultAsync(x=>x.CategoryId==id);if(c is null)return NotFound();if(!await IsOwner(c.Event))return Forbid();db.Categories.Remove(c);await db.SaveChangesAsync();return NoContent();}
 private bool Valid(CategoryRequest r)=>r.Distance>0&&r.MinAge>=0&&r.MaxAge>=r.MinAge&&r.EntryFee>=0; private async Task<Event?> Owned(int id){var o=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());return await db.Events.SingleOrDefaultAsync(x=>x.EventId==id&&x.OrganizerId==o.OrganizerId);} private async Task<bool> IsOwner(Event e){var o=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());return e.OrganizerId==o.OrganizerId;}
}
[ApiController, Route("api/enrollments"), Authorize(Roles="Participant")] public class EnrollmentsController(RaceDayDbContext db):ControllerBase {
 [HttpPost] public async Task<IActionResult> Create(EnrollmentRequest r){var p=await db.Participants.SingleAsync(x=>x.UserId==User.UserId());var c=await db.Categories.SingleOrDefaultAsync(x=>x.CategoryId==r.CategoryId);if(c is null)return BadRequest("Invalid category.");if(await db.Enrollments.AnyAsync(x=>x.ParticipantId==p.ParticipantId&&x.CategoryId==r.CategoryId))return Conflict("Already enrolled.");var e=new Enrollment{ParticipantId=p.ParticipantId,CategoryId=r.CategoryId};db.Enrollments.Add(e);await db.SaveChangesAsync();return Created($"api/enrollments/{e.EnrollmentId}",e);}
 [HttpGet] public async Task<IActionResult> Mine(){var p=await db.Participants.SingleAsync(x=>x.UserId==User.UserId());return Ok(await db.Enrollments.Where(x=>x.ParticipantId==p.ParticipantId).Include(x=>x.Category).ThenInclude(x=>x.Event).Include(x=>x.Result).ToListAsync());}
 [HttpDelete("{id:int}")] public async Task<IActionResult> Cancel(int id){var p=await db.Participants.SingleAsync(x=>x.UserId==User.UserId());var e=await db.Enrollments.SingleOrDefaultAsync(x=>x.EnrollmentId==id&&x.ParticipantId==p.ParticipantId);if(e is null)return NotFound();db.Enrollments.Remove(e);await db.SaveChangesAsync();return NoContent();}
}
[ApiController] public class EventEnrollmentController(RaceDayDbContext db):ControllerBase { [HttpGet("api/events/{eventId:int}/enrollments"),Authorize(Roles="Organiser")] public async Task<IActionResult> List(int eventId){var o=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());if(!await db.Events.AnyAsync(x=>x.EventId==eventId&&x.OrganizerId==o.OrganizerId))return Forbid();return Ok(await db.Enrollments.Where(x=>x.Category.EventId==eventId).Include(x=>x.Participant).Include(x=>x.Category).ToListAsync());} }
[ApiController, Route("api/results")] public class ResultsController(RaceDayDbContext db):ControllerBase {
 [HttpPost,Authorize(Roles="Organiser")] public async Task<IActionResult> Create(ResultRequest r){var e=await db.Enrollments.Include(x=>x.Category).ThenInclude(x=>x.Event).SingleOrDefaultAsync(x=>x.EnrollmentId==r.EnrollmentId);if(e is null||!await Owner(e.Category.Event))return Forbid();if(await db.Results.AnyAsync(x=>x.EnrollmentId==r.EnrollmentId))return Conflict();var x=new Result{EnrollmentId=r.EnrollmentId,FinishTime=r.FinishTime,Position=r.Position,Remarks=r.Remarks};db.Results.Add(x);await db.SaveChangesAsync();return Created($"api/results/{x.ResultId}",x);}
 [HttpPut("{id:int}"),Authorize(Roles="Organiser")] public async Task<IActionResult> Update(int id,UpdateResultRequest r){var x=await db.Results.Include(x=>x.Enrollment).ThenInclude(x=>x.Category).ThenInclude(x=>x.Event).SingleOrDefaultAsync(x=>x.ResultId==id);if(x is null)return NotFound();if(!await Owner(x.Enrollment.Category.Event))return Forbid();(x.FinishTime,x.Position,x.Remarks)=(r.FinishTime,r.Position,r.Remarks);await db.SaveChangesAsync();return Ok(x);}
 [HttpGet,Authorize(Roles="Participant")] public async Task<IActionResult> Mine(){var p=await db.Participants.SingleAsync(x=>x.UserId==User.UserId());return Ok(await db.Results.Where(x=>x.Enrollment.ParticipantId==p.ParticipantId).Include(x=>x.Enrollment).ThenInclude(x=>x.Category).ThenInclude(x=>x.Event).ToListAsync());}
 [HttpGet("/api/events/{eventId:int}/results"),Authorize] public async Task<IActionResult> EventResults(int eventId){if(!await db.Events.AnyAsync(x=>x.EventId==eventId))return NotFound();return Ok(await db.Results.Where(x=>x.Enrollment.Category.EventId==eventId).Include(x=>x.Enrollment).ThenInclude(x=>x.Participant).ToListAsync());}
 private async Task<bool> Owner(Event e){var o=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());return e.OrganizerId==o.OrganizerId;}
}
[ApiController, Route("api/users"), Authorize] public class UsersController(RaceDayDbContext db):ControllerBase {
 [HttpGet("profile")] public async Task<IActionResult> Profile()=>Ok(await ProfileData());
 [HttpPut("profile")] public async Task<IActionResult> Update(ProfileRequest r) { var u=await db.Users.Include(x=>x.Organizer).Include(x=>x.Participant).SingleAsync(x=>x.UserId==User.UserId()); if(u.Role==nameof(UserRole.Organiser)){if(u.Organizer is null)return BadRequest(); u.Organizer.OrganisationName=r.OrganisationName??u.Organizer.OrganisationName;u.Organizer.ContactName=r.ContactName??u.Organizer.ContactName;u.Organizer.Phone=r.Phone??u.Organizer.Phone;}else{if(u.Participant is null)return BadRequest();u.Participant.FirstName=r.FirstName??u.Participant.FirstName;u.Participant.LastName=r.LastName??u.Participant.LastName;u.Participant.DateOfBirth=r.DateOfBirth??u.Participant.DateOfBirth;u.Participant.Gender=r.Gender??u.Participant.Gender;u.Participant.EmergencyContact=r.EmergencyContact??u.Participant.EmergencyContact;u.Participant.ProfilePictureUrl=r.ProfilePictureUrl??u.Participant.ProfilePictureUrl;} await db.SaveChangesAsync();return Ok(await ProfileData()); }
 private async Task<object> ProfileData(){var u=await db.Users.Include(x=>x.Organizer).Include(x=>x.Participant).SingleAsync(x=>x.UserId==User.UserId());return new{u.UserId,u.Username,u.Email,u.Role,u.Organizer,u.Participant};}
}
[ApiController, Route("api/events")] public class EventsController(RaceDayDbContext db):ControllerBase {
 [HttpGet] public async Task<IActionResult> List()=>Ok(await db.Events.AsNoTracking().Include(e=>e.Organizer).Select(e=>new{e.EventId,e.EventName,e.Description,e.EventDate,e.Location,e.Distance,e.EventType,e.BannerImageUrl,e.Status,Organizer=e.Organizer.OrganisationName}).ToListAsync());
 [HttpGet("{id:int}")] public async Task<IActionResult> Get(int id){var e=await db.Events.AsNoTracking().Include(x=>x.Categories).SingleOrDefaultAsync(x=>x.EventId==id);return e is null?NotFound():Ok(e);}
 [HttpPost,Authorize(Roles="Organiser")] public async Task<IActionResult> Create(EventRequest r){if(!ValidEvent(r))return BadRequest("Event type must be run, walk or cycle and distance must be positive.");var org=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());var e=new Event{OrganizerId=org.OrganizerId,EventName=r.EventName,Description=r.Description,EventDate=r.EventDate,Location=r.Location,Distance=r.Distance,EventType=r.EventType.ToLower(),BannerImageUrl=r.BannerImageUrl,Status=r.Status??"Open"};db.Events.Add(e);await db.SaveChangesAsync();return CreatedAtAction(nameof(Get),new{id=e.EventId},e);}
 [HttpPut("{id:int}"),Authorize(Roles="Organiser")] public async Task<IActionResult> Update(int id,EventRequest r){var e=await OwnedEvent(id);if(e is null)return Forbid();if(!ValidEvent(r))return BadRequest();(e.EventName,e.Description,e.EventDate,e.Location,e.Distance,e.EventType,e.BannerImageUrl,e.Status)=(r.EventName,r.Description,r.EventDate,r.Location,r.Distance,r.EventType.ToLower(),r.BannerImageUrl,r.Status??e.Status);await db.SaveChangesAsync();return Ok(e);}
 [HttpDelete("{id:int}"),Authorize(Roles="Organiser")] public async Task<IActionResult> Delete(int id){var e=await OwnedEvent(id);if(e is null)return Forbid();db.Events.Remove(e);await db.SaveChangesAsync();return NoContent();}
 private bool ValidEvent(EventRequest r)=>r.Distance>0&&new[]{"run","walk","cycle"}.Contains(r.EventType.ToLower()); private async Task<Event?> OwnedEvent(int id){var org=await db.Organizers.SingleAsync(x=>x.UserId==User.UserId());return await db.Events.SingleOrDefaultAsync(x=>x.EventId==id&&x.OrganizerId==org.OrganizerId);}
}
