using System.ComponentModel.DataAnnotations;
namespace RaceDay.Api;
public enum UserRole { Organiser, Participant }
public class User { public int UserId { get; set; } [MaxLength(80)] public string Username { get; set; } = null!; [MaxLength(160)] public string Email { get; set; } = null!; public string PasswordHash { get; set; } = null!; [MaxLength(20)] public string Role { get; set; } = null!; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public Organizer? Organizer { get; set; } public Participant? Participant { get; set; } }
public class Organizer { public int OrganizerId { get; set; } public int UserId { get; set; } public User User { get; set; } = null!; [MaxLength(120)] public string OrganisationName { get; set; } = null!; [MaxLength(100)] public string ContactName { get; set; } = null!; [MaxLength(30)] public string Phone { get; set; } = null!; public List<Event> Events { get; set; } = []; }
public class Participant { public int ParticipantId { get; set; } public int UserId { get; set; } public User User { get; set; } = null!; [MaxLength(80)] public string FirstName { get; set; } = null!; [MaxLength(80)] public string LastName { get; set; } = null!; public DateOnly DateOfBirth { get; set; } [MaxLength(20)] public string Gender { get; set; } = null!; [MaxLength(160)] public string EmergencyContact { get; set; } = null!; [MaxLength(500)] public string? ProfilePictureUrl { get; set; } public List<Enrollment> Enrollments { get; set; } = []; }
public class Event { public int EventId { get; set; } public int OrganizerId { get; set; } public Organizer Organizer { get; set; } = null!; [MaxLength(160)] public string EventName { get; set; } = null!; [MaxLength(1000)] public string Description { get; set; } = null!; public DateOnly EventDate { get; set; } [MaxLength(160)] public string Location { get; set; } = null!; public decimal Distance { get; set; } [MaxLength(20)] public string EventType { get; set; } = null!; [MaxLength(500)] public string? BannerImageUrl { get; set; } [MaxLength(20)] public string Status { get; set; } = "Open"; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public List<Category> Categories { get; set; } = []; }
public class Category { public int CategoryId { get; set; } public int EventId { get; set; } public Event Event { get; set; } = null!; [MaxLength(100)] public string CategoryName { get; set; } = null!; public decimal Distance { get; set; } public int MinAge { get; set; } public int MaxAge { get; set; } public decimal EntryFee { get; set; } public List<Enrollment> Enrollments { get; set; } = []; }
public class Enrollment { public int EnrollmentId { get; set; } public int ParticipantId { get; set; } public Participant Participant { get; set; } = null!; public int CategoryId { get; set; } public Category Category { get; set; } = null!; public DateTime EnrollmentDate { get; set; } = DateTime.UtcNow; [MaxLength(20)] public string Status { get; set; } = "Active"; [MaxLength(20)] public string PaymentStatus { get; set; } = "Pending"; [MaxLength(30)] public string? BibNumber { get; set; } public Result? Result { get; set; } }
public class Result { public int ResultId { get; set; } public int EnrollmentId { get; set; } public Enrollment Enrollment { get; set; } = null!; public TimeOnly FinishTime { get; set; } public int Position { get; set; } [MaxLength(500)] public string? Remarks { get; set; } }
